# Docker File

# Use an existing node alpine image as base image
FROM node:20.14.0

# set the working directory
WORKDIR /build

# Copy the package.json file
COPY package.json .

# Install application dependencies.
RUN npm install

# build application
RUN npm run build

# Copy the rest of application files
COPY . .

# Expose the port
EXPOSE 3000

# Run the application
CMD ["npm","start"]
#RUN npm run start